### ISSUE TITLE
Error when compiling the kernel, error: unknown type name 'hot'

### ISSUE THREAD

**Issue by cristian-programmer** [davidaylaian/carbon#35]
When I build the make, I have problems, my compiler, He says
 error: unknown type name 'hot'
![carbonissuse](https://user-images.githubusercontent.com/16086319/49984273-5fc69700-ff35-11e8-8401-418494d7e704.png)

I followed the osdev tutorial and the cross compiler works, could it be that you used a different version to do it?
I use binutils 2.27 and gcc 6.20

I saw this YouTube video: https://www.youtube.com/watch?v=nnL_Lv19hdw&t=16514s
thanks!

**Comment by davidaylaian** [comment]
Hello, this keyword was included as a micro-optimization in older versions of Carbon, but it looks like your compiler doesn't like it. Unfortunately, I haven't had time to finish the new version and put it on Github. The new version shouldn't have this keyword. If you check back in a few months I should have that version up, but otherwise, you can fix this issue simply by getting rid of all of the occurrences of the hot keyword. The easiest way to do this would just be to [use a find and replace command recursively](https://stackoverflow.com/questions/60034/how-can-you-find-and-replace-text-in-a-file-using-the-windows-command-line-envir) in the carbon directory. Thanks for the interest in my OS!

**Comment by cristian-programmer** [comment]
Thank you very much for your reply, well, I will delete those keywords :),

**Comment by davidaylaian** [comment]
@cristian-programmer hi! Just wanted to say: the new version is finally being developed!

**Comment by cristian-programmer** [comment]
Thank you very much, I will be pending in the development: D.
